### ISSUE TITLE
No language parameter does not render as ruby as expected

### ISSUE THREAD

**Issue by pablaasmo** [catawiki/Prism#1]
If I try some code using the macro {code}, ie.e. without a language specification, you do not get the same as when using macro {code:ruby}.

Since ruby is the default language, according to documentation, I expected the two to look the same.
![screenshot_095](https://user-images.githubusercontent.com/1215134/30480669-4287787e-9a1b-11e7-892d-0a9cdf76abb2.png)

**Comment by siavashs** [comment]
@pablaasmo Thanks for reporting the issue, I will release v1.1.1 which includes this fix.
