### ISSUE TITLE
Does  the add-on perform any network communications or "phone home"?

### ISSUE THREAD

**Issue by hammondr** [catawiki/Prism#18]
Is all activity for this add-on performed on-site?  Are there any network calls outbound to anywhere else?  Thanks!

**Comment by siavashs** [comment]
@hammondr Please check [Privacy Policy](https://github.com/catawiki/Prism/blob/master/PRIVACY.md).

**Comment by terranisu** [comment]
@hammondr if somehow you still have any doubts, feel free to scrutinize the plugin's code.
