### ISSUE TITLE
Prism should support the same paramteres as original Jira macro

### ISSUE THREAD

**Issue by pablaasmo** [catawiki/Prism#2]
Since it replaces the original \{code\} macro, I think it should handle the original parameters for compatibility.

The Jira \{code\} macro has the paramteres:

- language
- title
- collapse
- linenumbers
- firstline
- theme

Currently only 'linenumbers' is recognized.
Adding 'language' should be the minimum to have compatibility.
I also thinks 'theme' should be available and have a default to mimic the same as original default ('Confluence').

'title' would have been nice to have. In our company we have used it often. 
'firstline' is also a nice feture, but I am not sure if it is possible with Prism. Possibly mapping it to 'data-start' option for 'linenumbers' in Prism. 
'collapse' I do not think is available in Prism.

**Comment by siavashs** [comment]
I'll put these on the list for the next release:
- [ ]  language
- [ ] title
- [ ] firstline

These feature require more effort and might be implemented in future:
- collapse
- theme

**Comment by siavashs** [comment]
[Version 1.2.0](https://github.com/catawiki/Prism/releases/tag/v1.2.0) is released.
