### ISSUE TITLE
Please release Jira 8.2.2 compatible version

### ISSUE THREAD

**Issue by jusfreeman** [catawiki/Prism#23]
Hi there,

Can you please release Jira 8.2.2 compatible version?

Thanks in advance!
Justin

**Comment by siavashs** [comment]
Hi @jusfreeman 
As I checked the plugin works on 8.2.2 so I will mark it as compatible in the marketplace.

**Comment by jusfreeman** [comment]
@siavashs thank you very much

You really should make this a paid plugin too.
