### ISSUE TITLE
Confluence

### ISSUE THREAD

**Issue by niklaskorz** [catawiki/Prism#3]
Any plans to make this plugin available as a Confluence plugin? If not, how hard would it be to port it myself?

**Comment by siavashs** [comment]
I have not looked into Confluence plugins yet but I think it should not be very hard to do this, I might look into it on a boring weekend, but you can also submit a PR.

**Comment by siavashs** [comment]
So as I checked it is possible to do this by creating a cross plugin and separating the application components as described here https://developer.atlassian.com/server/framework/atlassian-sdk/plugin-modules/
I'll test this soon.

**Comment by a-komarev** [comment]
Just noticed that open source [Markdown Macro Plugin](https://marketplace.atlassian.com/plugins/com.atlassian.plugins.confluence.markdown.confluence-markdown-macro/server/overview) generates code with prism classes, but doesn't have css nor js from it.

![screenshot from 2018-05-04 14-35-38](https://user-images.githubusercontent.com/1849174/39625937-773bb646-4fa8-11e8-9c23-57bb27907b4e.png)

Generates:
```html
<pre><code class="language-php">$var = 'test';
</code></pre>
```

Here are [sources of Markdown Macro Plugin](https://bitbucket.org/atlassianlabs/markdown-macro-for-confluence/src/bed352856f33?at=master), maybe it will be useful for you.

**Comment by siavashs** [comment]
Unfortunately no progress was made, but it's on my todo list and I'll look into it when I find some free time.

**Comment by siavashs** [comment]
I did some search today and found out that Atlassian has their new code macro open sourced, so anyone interested can open a PR against that repo to add more languages or even integrate PrismJS: https://bitbucket.org/atlassian/confluence-newcode-macro-plugin/overview
